---
- name: "[Ansible 1] On-premise Network & AWS DMS Preparation (HA Optimized)"
  hosts: proxy
  # hosts를 proxy로 설정했으므로, 앤시블은 인벤토리에 있는 모든 프록시를 훑습니다.
  become: yes
  vars_files:
    - group_vars/all/vault.yml
  vars:
    # 알려주신 실제 DB VIP 대역(10.2.3.x)으로 수정했습니다.
    onprem_vip_subnet: "10.2.3.0/24"

  tasks:
    ##########################################################
    # 0. 환경 정비 (Proxy 그룹 전체)
    # 어떤 Proxy가 컨트롤 타워가 될지 모르니 모두에게 무기를 쥐여줍니다.
    ##########################################################
    - name: 모든 Proxy 서버에 AWS SDK(boto3) 설치
      ansible.builtin.pip:
        name:
          - boto3
          - botocore
        executable: pip3
      # delegate_to를 삭제하여 모든 proxy 노드에 설치되게 합니다.

    ##########################################################
    # 1. AWS DMS 사전 준비 (IAM Role 생성)
    # '현재 이 플레이북을 실행 중인 노드'가 AWS API를 호출하도록 합니다.
    ##########################################################
    - name: DMS용 VPC Role 생성 (dms-vpc-role)
      # 특정 노드를 지칭하지 않고 run_once를 써서 한 번만 실행되게 합니다.
      run_once: true
      delegate_to: localhost
      become: no
      community.aws.iam_role:
        name: dms-vpc-role
        assume_role_policy_document: "{{ {
          'Version': '2012-10-17',
          'Statement': [{
            'Action': 'sts:AssumeRole',
            'Effect': 'Allow',
            'Principal': {'Service': 'dms.amazonaws.com'}
          }]
        } | to_json }}"
        managed_policies:
          - arn:aws:iam::aws:policy/service-role/AmazonDMSVPCManagementRole
        state: present

    - name: DMS용 로그 Role 생성 (dms-cloudwatch-logs-role)
      run_once: true
      delegate_to: localhost
      become: no
      community.aws.iam_role:
        name: dms-cloudwatch-logs-role
        assume_role_policy_document: "{{ {
          'Version': '2012-10-17',
          'Statement': [{
            'Action': 'sts:AssumeRole',
            'Effect': 'Allow',
            'Principal': {'Service': 'dms.amazonaws.com'}
          }]
        } | to_json }}"
        managed_policies:
          - arn:aws:iam::aws:policy/service-role/AmazonDMSCloudWatchLogsRole
        state: present

    ##########################################################
    # 2. Tailscale API를 호출하여 일회용 Auth Key 생성
    ##########################################################
    - name: Tailscale 임시 Auth Key 생성 (API 호출)
      run_once: true
      delegate_to: localhost
      become: no
      uri:
        url: "https://api.tailscale.com/api/v2/tailnet/{{ vault_tailnet }}/keys"
        method: POST
        user: "{{ vault_api_key }}"
        password: ""
        force_basic_auth: yes
        body_format: json
        body:
          capabilities:
            devices:
              create:
                reusable: false
                ephemeral: true
                preauthorized: true
                tags: [] 
          expirySeconds: 3600
      register: ts_api_result

    - name: 생성된 키 저장
      set_fact:
        dynamic_ts_key: "{{ ts_api_result.json.key }}"

    ##########################################################
    # 3. Role을 호출하여 Proxy 서버들에 Tailscale 설치 및 로그인
    ##########################################################
    - name: Tailscale 설치 및 설정 (Role 호출)
      include_role:
        name: tailscale_setup
      vars:
        internal_route: "{{ onprem_vip_subnet }}"
        auth_key: "{{ dynamic_ts_key }}"

    - name: Tailscale IP 추출
      command: tailscale ip -4
      register: proxy_ts_ip
      changed_when: false

    ##########################################################
    # 4. Terraform 변수 파일 생성 (onprem.auto.tfvars)
    ##########################################################
    - name: Terraform 변수 파일 생성 (onprem.auto.tfvars)
      # 파일 생성은 실행 중인 노드의 로컬 경로에만 하면 됩니다.
      run_once: true
      delegate_to: localhost
      become: no
      copy:
        content: |
          # Ansible에 의해 자동 생성된 변수 파일 (수정 금지)
          onprem_db_tailscale_ip = "{{ proxy_ts_ip.stdout | trim }}"
          tailscale_auth_key     = "{{ dynamic_ts_key }}"
        dest: "{{ playbook_dir | dirname }}/terraform/onprem.auto.tfvars"

- name: "최종 결과 확인"
  hosts: localhost
  tasks:
    - name: 생성 파일 안내
      debug:
        msg: 
          - "성공! 실제 DB 대역 10.2.3.0/24 경로 설정 완료"
          - "성공! AWS DMS IAM Role 생성 및 정책 연결 완료"
          - "성공! 테라폼 변수 파일 생성 완료: ansible/terraform/onprem.auto.tfvars"
